version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cloudmessenger-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - cloudmessenger-data:/usr/local/tomcat/cloudmessenger
      - ./firebase-service-account.json:/usr/local/tomcat/firebase-service-account.json
    environment:
      - JAVA_OPTS=-Xmx512m -Djava.security.egd=file:/dev/./urandom
    networks:
      - cloudmessenger-network

  # Опциональные сервисы для локальной разработки
  adminer:
    image: adminer:latest
    container_name: cloudmessenger-adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
    networks:
      - cloudmessenger-network
    depends_on:
      - app

networks:
  cloudmessenger-network:
    driver: bridge

volumes:
  cloudmessenger-data:
    driver: local 